import type { Constant } from './constants.d';

const constants: Constant = {
  AF: {
    icon: '🇦🇫',
    countryCode: 'AF',
    countryName: { en: 'Afghanistan', uk: 'Афганістан', ru: 'Афганистан' },
    callingCode: '93',
    regex: '^(\\+93|93)?[2-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '70 123 4567',
  },
  AL: {
    icon: '🇦🇱',
    countryCode: 'AL',
    countryName: { en: 'Albania', uk: 'Албанія', ru: 'Албания' },
    callingCode: '355',
    regex: '^(\\+355|355)?[67]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '67 123 4567',
  },
  DZ: {
    icon: '🇩🇿',
    countryCode: 'DZ',
    countryName: { en: 'Algeria', uk: 'Алжир', ru: 'Алжир' },
    callingCode: '213',
    regex: '^(\\+213|213)?[5-7]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '55 123 4567',
  },
  AD: {
    icon: '🇦🇩',
    countryCode: 'AD',
    countryName: { en: 'Andorra', uk: 'Андорра', ru: 'Андорра' },
    callingCode: '376',
    regex: '^(\\+376|376)?[3-9]\\d{5}$',
    mask: 'XXX XXX',
    placeholder: '312 345',
  },
  AO: {
    icon: '🇦🇴',
    countryCode: 'AO',
    countryName: { en: 'Angola', uk: 'Ангола', ru: 'Ангола' },
    callingCode: '244',
    regex: '^(\\+244|244)?9\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '923 123 456',
  },
  AR: {
    icon: '🇦🇷',
    countryCode: 'AR',
    countryName: { en: 'Argentina', uk: 'Аргентина', ru: 'Аргентина' },
    callingCode: '54',
    regex: '^(\\+54|54)?[1-9]\\d{9}$',
    mask: 'XX XXXX-XXXX',
    placeholder: '11 1234-5678',
  },
  AM: {
    icon: '🇦🇲',
    countryCode: 'AM',
    countryName: { en: 'Armenia', uk: 'Вірменія', ru: 'Армения' },
    callingCode: '374',
    regex: '^(\\+374|374)?9\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '91 123 456',
  },
  AU: {
    icon: '🇦🇺',
    countryCode: 'AU',
    countryName: { en: 'Australia', uk: 'Австралія', ru: 'Австралия' },
    callingCode: '61',
    regex: '^(\\+61|61)?[2-9]\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '412 345 678',
  },
  AT: {
    icon: '🇦🇹',
    countryCode: 'AT',
    countryName: { en: 'Austria', uk: 'Австрія', ru: 'Австрия' },
    callingCode: '43',
    regex: '^(\\+43|43)?[1-9]\\d{3,8}$',
    mask: 'XXX XXXXXXX',
    placeholder: '664 1234567',
  },
  AZ: {
    icon: '🇦🇿',
    countryCode: 'AZ',
    countryName: { en: 'Azerbaijan', uk: 'Азербайджан', ru: 'Азербайджан' },
    callingCode: '994',
    regex: '^(\\+994|994)?[50-59]\\d{7}$',
    mask: 'XX XXX XX XX',
    placeholder: '50 123 45 67',
  },
  BH: {
    icon: '🇧🇭',
    countryCode: 'BH',
    countryName: { en: 'Bahrain', uk: 'Бахрейн', ru: 'Бахрейн' },
    callingCode: '973',
    regex: '^(\\+973|973)?[3-9]\\d{7}$',
    mask: 'XXXX XXXX',
    placeholder: '3600 1234',
  },
  BD: {
    icon: '🇧🇩',
    countryCode: 'BD',
    countryName: { en: 'Bangladesh', uk: 'Бангладеш', ru: 'Бангладеш' },
    callingCode: '880',
    regex: '^(\\+880|880)?1[3-9]\\d{8}$',
    mask: 'XXXX-XXXXXX',
    placeholder: '1812-345678',
  },
  BY: {
    icon: '🇧🇾',
    countryCode: 'BY',
    countryName: { en: 'Belarus', uk: 'Білорусь', ru: 'Беларусь' },
    callingCode: '375',
    regex: '^(\\+375|375)?[2-9]\\d{7}$',
    mask: 'XX XXX-XX-XX',
    placeholder: '29 123-45-67',
  },
  BE: {
    icon: '🇧🇪',
    countryCode: 'BE',
    countryName: { en: 'Belgium', uk: 'Бельгія', ru: 'Бельгия' },
    callingCode: '32',
    regex: '^(\\+32|32)?[1-9]\\d{7}$',
    mask: 'XXX XX XX XX',
    placeholder: '470 12 34 56',
  },
  BJ: {
    icon: '🇧🇯',
    countryCode: 'BJ',
    countryName: { en: 'Benin', uk: 'Бенін', ru: 'Бенин' },
    callingCode: '229',
    regex: '^(\\+229|229)?[91-99]\\d{7}$',
    mask: 'XX XX XX XX',
    placeholder: '90 12 34 56',
  },
  BT: {
    icon: '🇧🇹',
    countryCode: 'BT',
    countryName: { en: 'Bhutan', uk: 'Бутан', ru: 'Бутан' },
    callingCode: '975',
    regex: '^(\\+975|975)?1\\d{7}$',
    mask: 'X XXX XXXX',
    placeholder: '17 123 456',
  },
  BO: {
    icon: '🇧🇴',
    countryCode: 'BO',
    countryName: { en: 'Bolivia', uk: 'Болівія', ru: 'Боливия' },
    callingCode: '591',
    regex: '^(\\+591|591)?[2-7]\\d{7}$',
    mask: 'X XXX XXXX',
    placeholder: '7 123 4567',
  },
  BA: {
    icon: '🇧🇦',
    countryCode: 'BA',
    countryName: {
      en: 'Bosnia and Herzegovina',
      uk: 'Боснія і Герцеговина',
      ru: 'Босния и Герцеговина',
    },
    callingCode: '387',
    regex: '^(\\+387|387)?6\\d{7}$',
    mask: 'XX XXX-XXX',
    placeholder: '61 123-456',
  },
  BW: {
    icon: '🇧🇼',
    countryCode: 'BW',
    countryName: { en: 'Botswana', uk: 'Ботсвана', ru: 'Ботсвана' },
    callingCode: '267',
    regex: '^(\\+267|267)?7\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '71 123 456',
  },
  BR: {
    icon: '🇧🇷',
    countryCode: 'BR',
    countryName: { en: 'Brazil', uk: 'Бразилія', ru: 'Бразилия' },
    callingCode: '55',
    regex: '^(\\+55|55)?[1-9]\\d{8}$',
    mask: '(XX) XXXXX-XXXX',
    placeholder: '(11) 91234-5678',
  },
  BN: {
    icon: '🇧🇳',
    countryCode: 'BN',
    countryName: { en: 'Brunei', uk: 'Бруней', ru: 'Бруней' },
    callingCode: '673',
    regex: '^(\\+673|673)?[2-8]\\d{6}$',
    mask: 'XXX XXXX',
    placeholder: '712 3456',
  },
  BG: {
    icon: '🇧🇬',
    countryCode: 'BG',
    countryName: { en: 'Bulgaria', uk: 'Болгарія', ru: 'Болгария' },
    callingCode: '359',
    regex: '^(\\+359|359)?[8-9]\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '87 123 4567',
  },
  BF: {
    icon: '🇧🇫',
    countryCode: 'BF',
    countryName: { en: 'Burkina Faso', uk: 'Буркіна-Фасо', ru: 'Буркина-Фасо' },
    callingCode: '226',
    regex: '^(\\+226|226)?[70-79]\\d{6}$',
    mask: 'XX XX XX XX',
    placeholder: '70 12 34 56',
  },
  BI: {
    icon: '🇧🇮',
    countryCode: 'BI',
    countryName: { en: 'Burundi', uk: 'Бурунді', ru: 'Бурунди' },
    callingCode: '257',
    regex: '^(\\+257|257)?7\\d{7}$',
    mask: 'XX XX XX XX',
    placeholder: '79 12 34 56',
  },
  KH: {
    icon: '🇰🇭',
    countryCode: 'KH',
    countryName: { en: 'Cambodia', uk: 'Камбоджа', ru: 'Камбоджа' },
    callingCode: '855',
    regex: '^(\\+855|855)?[1-9]\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '91 234 567',
  },
  CM: {
    icon: '🇨🇲',
    countryCode: 'CM',
    countryName: { en: 'Cameroon', uk: 'Камерун', ru: 'Камерун' },
    callingCode: '237',
    regex: '^(\\+237|237)?[2-7]\\d{7}$',
    mask: 'X XX XX XX XX',
    placeholder: '6 22 34 56 78',
  },
  CA: {
    icon: '🇨🇦',
    countryCode: 'CA',
    countryName: { en: 'Canada', uk: 'Канада', ru: 'Канада' },
    callingCode: '1',
    regex: '^(\\+1|1)?[2-9]\\d{9}$',
    mask: '(XXX) XXX-XXXX',
    placeholder: '(204) 234-5678',
  },
  CV: {
    icon: '🇨🇻',
    countryCode: 'CV',
    countryName: { en: 'Cape Verde', uk: 'Кабо-Верде', ru: 'Кабо-Верде' },
    callingCode: '238',
    regex: '^(\\+238|238)?[2-9]\\d{6}$',
    mask: 'XXX XX XX',
    placeholder: '991 12 34',
  },
  KY: {
    icon: '🇰🇾',
    countryCode: 'KY',
    countryName: {
      en: 'Cayman Islands',
      uk: 'Кайманові острови',
      ru: 'Каймановы острова',
    },
    callingCode: '1-345',
    regex: '^(\\+1-345|1-345)?[345]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '323-1234',
  },
  CF: {
    icon: '🇨🇫',
    countryCode: 'CF',
    countryName: {
      en: 'Central African Republic',
      uk: 'Центральноафриканська Республіка',
      ru: 'Центральноафриканская Республика',
    },
    callingCode: '236',
    regex: '^(\\+236|236)?[7-8]\\d{7}$',
    mask: 'XX XX XX XX',
    placeholder: '70 12 34 56',
  },
  TD: {
    icon: '🇹🇩',
    countryCode: 'TD',
    countryName: { en: 'Chad', uk: 'Чад', ru: 'Чад' },
    callingCode: '235',
    regex: '^(\\+235|235)?[7-9]\\d{7}$',
    mask: 'XX XX XX XX',
    placeholder: '63 12 34 56',
  },
  CL: {
    icon: '🇨🇱',
    countryCode: 'CL',
    countryName: { en: 'Chile', uk: 'Чилі', ru: 'Чили' },
    callingCode: '56',
    regex: '^(\\+56|56)?[2-9]\\d{8}$',
    mask: 'X XXXX XXXX',
    placeholder: '9 1234 5678',
  },
  CN: {
    icon: '🇨🇳',
    countryCode: 'CN',
    countryName: { en: 'China', uk: 'Китай', ru: 'Китай' },
    callingCode: '86',
    regex: '^(\\+86|86)?1[3-9]\\d{9}$',
    mask: 'XXX XXXX XXXX',
    placeholder: '131 2345 6789',
  },
  CO: {
    icon: '🇨🇴',
    countryCode: 'CO',
    countryName: { en: 'Colombia', uk: 'Колумбія', ru: 'Колумбия' },
    callingCode: '57',
    regex: '^(\\+57|57)?[1-9]\\d{9}$',
    mask: 'XXX XXX XXXX',
    placeholder: '321 123 4567',
  },
  KM: {
    icon: '🇰🇲',
    countryCode: 'KM',
    countryName: { en: 'Comoros', uk: 'Комори', ru: 'Коморы' },
    callingCode: '269',
    regex: '^(\\+269|269)?3\\d{6}$',
    mask: 'XXX XX XX',
    placeholder: '321 23 45',
  },
  CG: {
    icon: '🇨🇬',
    countryCode: 'CG',
    countryName: { en: 'Congo', uk: 'Конго', ru: 'Конго' },
    callingCode: '242',
    regex: '^(\\+242|242)?[7-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '06 123 4567',
  },
  CD: {
    icon: '🇨🇩',
    countryCode: 'CD',
    countryName: { en: 'Congo (DRC)', uk: 'Конго (ДРК)', ru: 'Конго (ДРК)' },
    callingCode: '243',
    regex: '^(\\+243|243)?[7-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '99 123 4567',
  },
  CR: {
    icon: '🇨🇷',
    countryCode: 'CR',
    countryName: { en: 'Costa Rica', uk: 'Коста-Ріка', ru: 'Коста-Рика' },
    callingCode: '506',
    regex: '^(\\+506|506)?[2-8]\\d{6}$',
    mask: 'XXXX-XXXX',
    placeholder: '8312-3456',
  },
  CI: {
    icon: '🇨🇮',
    countryCode: 'CI',
    countryName: { en: "Côte d'Ivoire", uk: "Кот-д'Івуар", ru: "Кот-д'Ивуар" },
    callingCode: '225',
    regex: '^(\\+225|225)?[0-9]\\d{7}$',
    mask: 'XX XX XX XX XX',
    placeholder: '01 23 45 67 89',
  },
  HR: {
    icon: '🇭🇷',
    countryCode: 'HR',
    countryName: { en: 'Croatia', uk: 'Хорватія', ru: 'Хорватия' },
    callingCode: '385',
    regex: '^(\\+385|385)?[1-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '91 234 5678',
  },
  CU: {
    icon: '🇨🇺',
    countryCode: 'CU',
    countryName: { en: 'Cuba', uk: 'Куба', ru: 'Куба' },
    callingCode: '53',
    regex: '^(\\+53|53)?[2-9]\\d{7}$',
    mask: 'X XXX XXXX',
    placeholder: '5 123 4567',
  },
  CY: {
    icon: '🇨🇾',
    countryCode: 'CY',
    countryName: { en: 'Cyprus', uk: 'Кіпр', ru: 'Кипр' },
    callingCode: '357',
    regex: '^(\\+357|357)?[2-9]\\d{6}$',
    mask: 'XX XXXXXX',
    placeholder: '96 123456',
  },
  CZ: {
    icon: '🇨🇿',
    countryCode: 'CZ',
    countryName: { en: 'Czech Republic', uk: 'Чехія', ru: 'Чехия' },
    callingCode: '420',
    regex: '^(\\+420|420)?[2-9]\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '601 123 456',
  },
  DK: {
    icon: '🇩🇰',
    countryCode: 'DK',
    countryName: { en: 'Denmark', uk: 'Данія', ru: 'Дания' },
    callingCode: '45',
    regex: '^(\\+45|45)?[2-9]\\d{7}$',
    mask: 'XX XX XX XX',
    placeholder: '32 12 34 56',
  },
  DJ: {
    icon: '🇩🇯',
    countryCode: 'DJ',
    countryName: { en: 'Djibouti', uk: 'Джибуті', ru: 'Джибути' },
    callingCode: '253',
    regex: '^(\\+253|253)?[2-9]\\d{6}$',
    mask: 'XX XX XX XX',
    placeholder: '77 12 34 56',
  },
  DM: {
    icon: '🇩🇲',
    countryCode: 'DM',
    countryName: { en: 'Dominica', uk: 'Домініка', ru: 'Доминика' },
    callingCode: '1767',
    regex: '^(\\+1767|1767)?[1-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '225-1234',
  },
  DO: {
    icon: '🇩🇴',
    countryCode: 'DO',
    countryName: {
      en: 'Dominican Republic',
      uk: 'Домініканська Республіка',
      ru: 'Доминиканская Республика',
    },
    callingCode: '1809',
    regex: '^(\\+1809|1809)?[1-9]\\d{7}$',
    mask: 'XXX-XXXX',
    placeholder: '809-234-5678',
  },
  EC: {
    icon: '🇪🇨',
    countryCode: 'EC',
    countryName: { en: 'Ecuador', uk: 'Еквадор', ru: 'Эквадор' },
    callingCode: '593',
    regex: '^(\\+593|593)?[2-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '99 123 4567',
  },
  EG: {
    icon: '🇪🇬',
    countryCode: 'EG',
    countryName: { en: 'Egypt', uk: 'Єгипет', ru: 'Египет' },
    callingCode: '20',
    regex: '^(\\+20|20)?[1-9]\\d{8}$',
    mask: 'XXX XXX XXXX',
    placeholder: '100 123 4567',
  },
  SV: {
    icon: '🇸🇻',
    countryCode: 'SV',
    countryName: { en: 'El Salvador', uk: 'Сальвадор', ru: 'Сальвадор' },
    callingCode: '503',
    regex: '^(\\+503|503)?[2-9]\\d{7}$',
    mask: 'XXXX-XXXX',
    placeholder: '7012-3456',
  },
  GQ: {
    icon: '🇬🇶',
    countryCode: 'GQ',
    countryName: {
      en: 'Equatorial Guinea',
      uk: 'Екваторіальна Гвінея',
      ru: 'Экваториальная Гвинея',
    },
    callingCode: '240',
    regex: '^(\\+240|240)?[2-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '22 123 4567',
  },
  ER: {
    icon: '🇪🇷',
    countryCode: 'ER',
    countryName: { en: 'Eritrea', uk: 'Еритрея', ru: 'Эритрея' },
    callingCode: '291',
    regex: '^(\\+291|291)?[2-9]\\d{6}$',
    mask: 'X XXX XXX',
    placeholder: '7 123 456',
  },
  EE: {
    icon: '🇪🇪',
    countryCode: 'EE',
    countryName: { en: 'Estonia', uk: 'Естонія', ru: 'Эстония' },
    callingCode: '372',
    regex: '^(\\+372|372)?[2-9]\\d{7}$',
    mask: 'XXXX XXXX',
    placeholder: '5123 4567',
  },
  ET: {
    icon: '🇪🇹',
    countryCode: 'ET',
    countryName: { en: 'Ethiopia', uk: 'Ефіопія', ru: 'Эфиопия' },
    callingCode: '251',
    regex: '^(\\+251|251)?[1-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '91 123 4567',
  },
  FJ: {
    icon: '🇫🇯',
    countryCode: 'FJ',
    countryName: { en: 'Fiji', uk: 'Фіджі', ru: 'Фиджи' },
    callingCode: '679',
    regex: '^(\\+679|679)?7\\d{6}$',
    mask: 'XXX XXXX',
    placeholder: '701 2345',
  },
  FI: {
    icon: '🇫🇮',
    countryCode: 'FI',
    countryName: { en: 'Finland', uk: 'Фінляндія', ru: 'Финляндия' },
    callingCode: '358',
    regex: '^(\\+358|358)?[0-9]\\d{6,9}$',
    mask: 'XX XXX XXXX',
    placeholder: '41 234 5678',
  },
  FR: {
    icon: '🇫🇷',
    countryCode: 'FR',
    countryName: { en: 'France', uk: 'Франція', ru: 'Франция' },
    callingCode: '33',
    regex: '^(\\+33|33)?[1-9]\\d{8}$',
    mask: 'X XX XX XX XX',
    placeholder: '6 12 34 56 78',
  },
  GA: {
    icon: '🇬🇦',
    countryCode: 'GA',
    countryName: { en: 'Gabon', uk: 'Габон', ru: 'Габон' },
    callingCode: '241',
    regex: '^(\\+241|241)?[2-9]\\d{6}$',
    mask: 'X XX XX XX',
    placeholder: '6 12 34 56',
  },
  GM: {
    icon: '🇬🇲',
    countryCode: 'GM',
    countryName: { en: 'Gambia', uk: 'Гамбія', ru: 'Гамбия' },
    callingCode: '220',
    regex: '^(\\+220|220)?[3-9]\\d{6}$',
    mask: 'XXX XXXX',
    placeholder: '301 2345',
  },
  GE: {
    icon: '🇬🇪',
    countryCode: 'GE',
    countryName: { en: 'Georgia', uk: 'Грузія', ru: 'Грузия' },
    callingCode: '995',
    regex: '^(\\+995|995)?[3-9]\\d{8}$',
    mask: 'XXX XX XX XX',
    placeholder: '555 12 34 56',
  },
  DE: {
    icon: '🇩🇪',
    countryCode: 'DE',
    countryName: { en: 'Germany', uk: 'Німеччина', ru: 'Германия' },
    callingCode: '49',
    regex: '^(\\+49|49)?[1-9]\\d{7,10}$',
    mask: 'XXXX XXXXXXXX',
    placeholder: '151 12345678',
  },
  GH: {
    icon: '🇬🇭',
    countryCode: 'GH',
    countryName: { en: 'Ghana', uk: 'Гана', ru: 'Гана' },
    callingCode: '233',
    regex: '^(\\+233|233)?[2-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '23 123 4567',
  },
  GR: {
    icon: '🇬🇷',
    countryCode: 'GR',
    countryName: { en: 'Greece', uk: 'Греція', ru: 'Греция' },
    callingCode: '30',
    regex: '^(\\+30|30)?[1-9]\\d{8}$',
    mask: 'XXX XXX XXXX',
    placeholder: '691 234 5678',
  },
  GD: {
    icon: '🇬🇩',
    countryCode: 'GD',
    countryName: { en: 'Grenada', uk: 'Гренада', ru: 'Гренада' },
    callingCode: '1-473',
    regex: '^(\\+1-473|1-473)?[1-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '403-1234',
  },
  GU: {
    icon: '🇬🇺',
    countryCode: 'GU',
    countryName: { en: 'Guam', uk: 'Гуам', ru: 'Гуам' },
    callingCode: '1-671',
    regex: '^(\\+1-671|1-671)?[1-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '300-1234',
  },
  GT: {
    icon: '🇬🇹',
    countryCode: 'GT',
    countryName: { en: 'Guatemala', uk: 'Гватемала', ru: 'Гватемала' },
    callingCode: '502',
    regex: '^(\\+502|502)?[2-9]\\d{7}$',
    mask: 'XXXX-XXXX',
    placeholder: '5123-4567',
  },
  GN: {
    icon: '🇬🇳',
    countryCode: 'GN',
    countryName: { en: 'Guinea', uk: 'Гвінея', ru: 'Гвинея' },
    callingCode: '224',
    regex: '^(\\+224|224)?[2-9]\\d{7}$',
    mask: 'XX XX XX XX',
    placeholder: '60 12 34 56',
  },
  GW: {
    icon: '🇬🇼',
    countryCode: 'GW',
    countryName: {
      en: 'Guinea-Bissau',
      uk: 'Гвінея-Бісау',
      ru: 'Гвинея-Бисау',
    },
    callingCode: '245',
    regex: '^(\\+245|245)?[2-9]\\d{7}$',
    mask: 'X XXX XXXX',
    placeholder: '5 123 4567',
  },
  GY: {
    icon: '🇬🇾',
    countryCode: 'GY',
    countryName: { en: 'Guyana', uk: 'Гаяна', ru: 'Гайана' },
    callingCode: '592',
    regex: '^(\\+592|592)?[2-9]\\d{7}$',
    mask: 'XXX-XXXX',
    placeholder: '609-1234',
  },
  HT: {
    icon: '🇭🇹',
    countryCode: 'HT',
    countryName: { en: 'Haiti', uk: 'Гаїті', ru: 'Гаити' },
    callingCode: '509',
    regex: '^(\\+509|509)?[2-9]\\d{7}$',
    mask: 'XX XX XXXX',
    placeholder: '34 10 1234',
  },
  HN: {
    icon: '🇭🇳',
    countryCode: 'HN',
    countryName: { en: 'Honduras', uk: 'Гондурас', ru: 'Гондурас' },
    callingCode: '504',
    regex: '^(\\+504|504)?[2-9]\\d{7}$',
    mask: 'XXXX-XXXX',
    placeholder: '9123-4567',
  },
  HU: {
    icon: '🇭🇺',
    countryCode: 'HU',
    countryName: { en: 'Hungary', uk: 'Угорщина', ru: 'Венгрия' },
    callingCode: '36',
    regex: '^(\\+36|36)?[1-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '20 123 4567',
  },
  IS: {
    icon: '🇮🇸',
    countryCode: 'IS',
    countryName: { en: 'Iceland', uk: 'Ісландія', ru: 'Исландия' },
    callingCode: '354',
    regex: '^(\\+354|354)?[1-9]\\d{6}$',
    mask: 'XXX XXXX',
    placeholder: '611 2345',
  },
  IN: {
    icon: '🇮🇳',
    countryCode: 'IN',
    countryName: { en: 'India', uk: 'Індія', ru: 'Индия' },
    callingCode: '91',
    regex: '^(\\+91|91)?[7-9]\\d{9}$',
    mask: 'XXXXX XXXXX',
    placeholder: '81234 56789',
  },
  ID: {
    icon: '🇮🇩',
    countryCode: 'ID',
    countryName: { en: 'Indonesia', uk: 'Індонезія', ru: 'Индонезия' },
    callingCode: '62',
    regex: '^(\\+62|62)?[1-9]\\d{8,9}$',
    mask: 'XXX-XXX-XXXX',
    placeholder: '812-345-6789',
  },
  IR: {
    icon: '🇮🇷',
    countryCode: 'IR',
    countryName: { en: 'Iran', uk: 'Іран', ru: 'Иран' },
    callingCode: '98',
    regex: '^(\\+98|98)?[1-9]\\d{8}$',
    mask: 'XXX XXX XXXX',
    placeholder: '912 345 6789',
  },
  IQ: {
    icon: '🇮🇶',
    countryCode: 'IQ',
    countryName: { en: 'Iraq', uk: 'Ірак', ru: 'Ирак' },
    callingCode: '964',
    regex: '^(\\+964|964)?[7-9]\\d{8}$',
    mask: 'XXX XXX XXXX',
    placeholder: '790 123 4567',
  },
  IE: {
    icon: '🇮🇪',
    countryCode: 'IE',
    countryName: { en: 'Ireland', uk: 'Ірландія', ru: 'Ирландия' },
    callingCode: '353',
    regex: '^(\\+353|353)?[1-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '85 012 3456',
  },
  IL: {
    icon: '🇮🇱',
    countryCode: 'IL',
    countryName: { en: 'Israel', uk: 'Ізраїль', ru: 'Израиль' },
    callingCode: '972',
    regex: '^(\\+972|972)?[2-9]\\d{7}$',
    mask: 'XX-XXX-XXXX',
    placeholder: '50-123-4567',
  },
  IT: {
    icon: '🇮🇹',
    countryCode: 'IT',
    countryName: { en: 'Italy', uk: 'Італія', ru: 'Италия' },
    callingCode: '39',
    regex: '^(\\+39|39)?[1-9]\\d{8}$',
    mask: 'XXX XXX XXXX',
    placeholder: '312 345 6789',
  },
  JM: {
    icon: '🇯🇲',
    countryCode: 'JM',
    countryName: { en: 'Jamaica', uk: 'Ямайка', ru: 'Ямайка' },
    callingCode: '1876',
    regex: '^(\\+1876|1876)?[1-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '210-1234',
  },
  JP: {
    icon: '🇯🇵',
    countryCode: 'JP',
    countryName: { en: 'Japan', uk: 'Японія', ru: 'Япония' },
    callingCode: '81',
    regex: '^(\\+81|81)?[1-9]\\d{8}$',
    mask: 'XX-XXXX-XXXX',
    placeholder: '90-1234-5678',
  },
  JO: {
    icon: '🇯🇴',
    countryCode: 'JO',
    countryName: { en: 'Jordan', uk: 'Йорданія', ru: 'Иордания' },
    callingCode: '962',
    regex: '^(\\+962|962)?[7-9]\\d{8}$',
    mask: 'XX XXXX XXXX',
    placeholder: '79 1234 5678',
  },
  KZ: {
    icon: '🇰🇿',
    countryCode: 'KZ',
    countryName: { en: 'Kazakhstan', uk: 'Казахстан', ru: 'Казахстан' },
    callingCode: '7',
    regex: '^(\\+7|7)?[1-9]\\d{9}$',
    mask: 'XXX XXX-XX-XX',
    placeholder: '771 234-56-78',
  },
  KE: {
    icon: '🇰🇪',
    countryCode: 'KE',
    countryName: { en: 'Kenya', uk: 'Кенія', ru: 'Кения' },
    callingCode: '254',
    regex: '^(\\+254|254)?[7-9]\\d{8}$',
    mask: 'XXX XXXXXX',
    placeholder: '712 123456',
  },
  KI: {
    icon: '🇰🇮',
    countryCode: 'KI',
    countryName: { en: 'Kiribati', uk: 'Кірибаті', ru: 'Кирибати' },
    callingCode: '686',
    regex: '^(\\+686|686)?[2-9]\\d{5}$',
    mask: 'XX XXX',
    placeholder: '72 001',
  },
  KW: {
    icon: '🇰🇼',
    countryCode: 'KW',
    countryName: { en: 'Kuwait', uk: 'Кувейт', ru: 'Кувейт' },
    callingCode: '965',
    regex: '^(\\+965|965)?[2-9]\\d{6}$',
    mask: 'XXXX XXXX',
    placeholder: '5000 0000',
  },
  KG: {
    icon: '🇰🇬',
    countryCode: 'KG',
    countryName: { en: 'Kyrgyzstan', uk: 'Киргизстан', ru: 'Киргизия' },
    callingCode: '996',
    regex: '^(\\+996|996)?[7-9]\\d{8}$',
    mask: 'XXX XXXXXX',
    placeholder: '700 123456',
  },
  LA: {
    icon: '🇱🇦',
    countryCode: 'LA',
    countryName: { en: 'Laos', uk: 'Лаос', ru: 'Лаос' },
    callingCode: '856',
    regex: '^(\\+856|856)?[2-9]\\d{8}$',
    mask: 'XX XX XXX XXX',
    placeholder: '20 23 123 456',
  },
  LV: {
    icon: '🇱🇻',
    countryCode: 'LV',
    countryName: { en: 'Latvia', uk: 'Латвія', ru: 'Латвия' },
    callingCode: '371',
    regex: '^(\\+371|371)?[2-9]\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '21 234 567',
  },
  LB: {
    icon: '🇱🇧',
    countryCode: 'LB',
    countryName: { en: 'Lebanon', uk: 'Ліван', ru: 'Ливан' },
    callingCode: '961',
    regex: '^(\\+961|961)?[1-9]\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '71 123 456',
  },
  LS: {
    icon: '🇱🇸',
    countryCode: 'LS',
    countryName: { en: 'Lesotho', uk: 'Лесото', ru: 'Лесото' },
    callingCode: '266',
    regex: '^(\\+266|266)?[2-9]\\d{6}$',
    mask: 'X XXX XXXX',
    placeholder: '5 012 3456',
  },
  LR: {
    icon: '🇱🇷',
    countryCode: 'LR',
    countryName: { en: 'Liberia', uk: 'Ліберія', ru: 'Либерия' },
    callingCode: '231',
    regex: '^(\\+231|231)?[2-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '77 012 3456',
  },
  LY: {
    icon: '🇱🇾',
    countryCode: 'LY',
    countryName: { en: 'Libya', uk: 'Лівія', ru: 'Ливия' },
    callingCode: '218',
    regex: '^(\\+218|218)?[2-9]\\d{7}$',
    mask: 'XX-XXX-XXXX',
    placeholder: '91-234-5678',
  },
  LI: {
    icon: '🇱🇮',
    countryCode: 'LI',
    countryName: { en: 'Liechtenstein', uk: 'Ліхтенштейн', ru: 'Лихтенштейн' },
    callingCode: '423',
    regex: '^(\\+423|423)?[2-9]\\d{6}$',
    mask: 'XXX XX XX',
    placeholder: '660 12 34',
  },
  LT: {
    icon: '🇱🇹',
    countryCode: 'LT',
    countryName: { en: 'Lithuania', uk: 'Литва', ru: 'Литва' },
    callingCode: '370',
    regex: '^(\\+370|370)?[6-9]\\d{7}$',
    mask: 'XXX XXXXX',
    placeholder: '612 34567',
  },
  LU: {
    icon: '🇱🇺',
    countryCode: 'LU',
    countryName: { en: 'Luxembourg', uk: 'Люксембург', ru: 'Люксембург' },
    callingCode: '352',
    regex: '^(\\+352|352)?[2-9]\\d{6}$',
    mask: 'XXX XXX XXX',
    placeholder: '628 123 456',
  },
  MO: {
    icon: '🇲🇴',
    countryCode: 'MO',
    countryName: { en: 'Macau', uk: 'Макао', ru: 'Макао' },
    callingCode: '853',
    regex: '^(\\+853|853)?[6-9]\\d{5}$',
    mask: 'XXXX XXXX',
    placeholder: '6612 3456',
  },
  MK: {
    icon: '🇲🇰',
    countryCode: 'MK',
    countryName: {
      en: 'North Macedonia',
      uk: 'Північна Македонія',
      ru: 'Северная Македония',
    },
    callingCode: '389',
    regex: '^(\\+389|389)?[7-9]\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '72 345 678',
  },
  MG: {
    icon: '🇲🇬',
    countryCode: 'MG',
    countryName: { en: 'Madagascar', uk: 'Мадагаскар', ru: 'Мадагаскар' },
    callingCode: '261',
    regex: '^(\\+261|261)?[3-9]\\d{7}$',
    mask: 'XX XX XXX XX',
    placeholder: '32 12 345 67',
  },
  MW: {
    icon: '🇲🇼',
    countryCode: 'MW',
    countryName: { en: 'Malawi', uk: 'Малаві', ru: 'Малави' },
    callingCode: '265',
    regex: '^(\\+265|265)?[2-9]\\d{7}$',
    mask: 'X XXXX XXXX',
    placeholder: '9 9123 4567',
  },
  MY: {
    icon: '🇲🇾',
    countryCode: 'MY',
    countryName: { en: 'Malaysia', uk: 'Малайзія', ru: 'Малайзия' },
    callingCode: '60',
    regex: '^(\\+60|60)?[1-9]\\d{7}$',
    mask: 'XX-XXX XXXX',
    placeholder: '12-345 6789',
  },
  MV: {
    icon: '🇲🇻',
    countryCode: 'MV',
    countryName: { en: 'Maldives', uk: 'Мальдіви', ru: 'Мальдивы' },
    callingCode: '960',
    regex: '^(\\+960|960)?[2-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '771-2345',
  },
  ML: {
    icon: '🇲🇱',
    countryCode: 'ML',
    countryName: { en: 'Mali', uk: 'Малі', ru: 'Мали' },
    callingCode: '223',
    regex: '^(\\+223|223)?[6-9]\\d{7}$',
    mask: 'XX XX XX XX',
    placeholder: '65 12 34 56',
  },
  MT: {
    icon: '🇲🇹',
    countryCode: 'MT',
    countryName: { en: 'Malta', uk: 'Мальта', ru: 'Мальта' },
    callingCode: '356',
    regex: '^(\\+356|356)?[2-9]\\d{7}$',
    mask: 'XXXX XXXX',
    placeholder: '9696 1234',
  },
  MH: {
    icon: '🇲🇭',
    countryCode: 'MH',
    countryName: {
      en: 'Marshall Islands',
      uk: 'Маршаллові Острови',
      ru: 'Маршалловы Острова',
    },
    callingCode: '692',
    regex: '^(\\+692|692)?[2-9]\\d{5}$',
    mask: 'XXX-XXXX',
    placeholder: '235-1234',
  },
  MR: {
    icon: '🇲🇷',
    countryCode: 'MR',
    countryName: { en: 'Mauritania', uk: 'Мавританія', ru: 'Мавритания' },
    callingCode: '222',
    regex: '^(\\+222|222)?[2-9]\\d{7}$',
    mask: 'XX XX XX XX',
    placeholder: '22 12 34 56',
  },
  MU: {
    icon: '🇲🇺',
    countryCode: 'MU',
    countryName: { en: 'Mauritius', uk: 'Маврикій', ru: 'Маврикий' },
    callingCode: '230',
    regex: '^(\\+230|230)?[5-9]\\d{6}$',
    mask: 'XXXX XXXX',
    placeholder: '5251 2345',
  },
  YT: {
    icon: '🇾🇹',
    countryCode: 'YT',
    countryName: { en: 'Mayotte', uk: 'Майотта', ru: 'Майотта' },
    callingCode: '262',
    regex: '^(\\+262|262)?[2-9]\\d{6}$',
    mask: 'XXX XX XX XX',
    placeholder: '639 12 34 56',
  },
  MX: {
    icon: '🇲🇽',
    countryCode: 'MX',
    countryName: { en: 'Mexico', uk: 'Мексика', ru: 'Мексика' },
    callingCode: '52',
    regex: '^(\\+52|52)?[1-9]\\d{9}$',
    mask: 'XXX XXX XXXX',
    placeholder: '222 123 4567',
  },
  FM: {
    icon: '🇫🇲',
    countryCode: 'FM',
    countryName: { en: 'Micronesia', uk: 'Мікронезія', ru: 'Микронезия' },
    callingCode: '691',
    regex: '^(\\+691|691)?[2-9]\\d{5}$',
    mask: 'XXX XXXX',
    placeholder: '350 1234',
  },
  MD: {
    icon: '🇲🇩',
    countryCode: 'MD',
    countryName: { en: 'Moldova', uk: 'Молдова', ru: 'Молдова' },
    callingCode: '373',
    regex: '^(\\+373|373)?[2-9]\\d{7}$',
    mask: 'XXXX XXXX',
    placeholder: '6212 3456',
  },
  MC: {
    icon: '🇲🇨',
    countryCode: 'MC',
    countryName: { en: 'Monaco', uk: 'Монако', ru: 'Монако' },
    callingCode: '377',
    regex: '^(\\+377|377)?[2-9]\\d{6}$',
    mask: 'XX XX XX XX',
    placeholder: '06 12 34 56',
  },
  MN: {
    icon: '🇲🇳',
    countryCode: 'MN',
    countryName: { en: 'Mongolia', uk: 'Монголія', ru: 'Монголия' },
    callingCode: '976',
    regex: '^(\\+976|976)?[1-9]\\d{7}$',
    mask: 'XXXX XXXX',
    placeholder: '8812 3456',
  },
  ME: {
    icon: '🇲🇪',
    countryCode: 'ME',
    countryName: { en: 'Montenegro', uk: 'Чорногорія', ru: 'Черногория' },
    callingCode: '382',
    regex: '^(\\+382|382)?[2-9]\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '67 123 456',
  },
  MS: {
    icon: '🇲🇸',
    countryCode: 'MS',
    countryName: { en: 'Montserrat', uk: 'Монтсеррат', ru: 'Монтсеррат' },
    callingCode: '1-664',
    regex: '^(\\+1-664|1-664)?[1-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '492-1234',
  },
  MA: {
    icon: '🇲🇦',
    countryCode: 'MA',
    countryName: { en: 'Morocco', uk: 'Марокко', ru: 'Марокко' },
    callingCode: '212',
    regex: '^(\\+212|212)?[6-7]\\d{8}$',
    mask: 'XXX-XXXXXX',
    placeholder: '650-123456',
  },
  MZ: {
    icon: '🇲🇿',
    countryCode: 'MZ',
    countryName: { en: 'Mozambique', uk: 'Мозамбік', ru: 'Мозамбик' },
    callingCode: '258',
    regex: '^(\\+258|258)?[8-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '82 123 4567',
  },
  MM: {
    icon: '🇲🇲',
    countryCode: 'MM',
    countryName: { en: 'Myanmar', uk: "М'янма", ru: 'Мьянма' },
    callingCode: '95',
    regex: '^(\\+95|95)?9\\d{7,8}$',
    mask: 'XX XXX XXXX',
    placeholder: '09 212 3456',
  },
  NA: {
    icon: '🇳🇦',
    countryCode: 'NA',
    countryName: { en: 'Namibia', uk: 'Намібія', ru: 'Намибия' },
    callingCode: '264',
    regex: '^(\\+264|264)?[1-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '81 123 4567',
  },
  NR: {
    icon: '🇳🇷',
    countryCode: 'NR',
    countryName: { en: 'Nauru', uk: 'Науру', ru: 'Науру' },
    callingCode: '674',
    regex: '^(\\+674|674)?[2-9]\\d{5}$',
    mask: 'XXX XXXX',
    placeholder: '555 1234',
  },
  NP: {
    icon: '🇳🇵',
    countryCode: 'NP',
    countryName: { en: 'Nepal', uk: 'Непал', ru: 'Непал' },
    callingCode: '977',
    regex: '^(\\+977|977)?[1-9]\\d{8}$',
    mask: 'XXX-XXX-XXXX',
    placeholder: '984-123-4567',
  },
  NL: {
    icon: '🇳🇱',
    countryCode: 'NL',
    countryName: { en: 'Netherlands', uk: 'Нідерланди', ru: 'Нидерланды' },
    callingCode: '31',
    regex: '^(\\+31|31)?[1-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '06 12345678',
  },
  NZ: {
    icon: '🇳🇿',
    countryCode: 'NZ',
    countryName: {
      en: 'New Zealand',
      uk: 'Нова Зеландія',
      ru: 'Новая Зеландия',
    },
    callingCode: '64',
    regex: '^(\\+64|64)?[2-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '21 123 4567',
  },
  NI: {
    icon: '🇳🇮',
    countryCode: 'NI',
    countryName: { en: 'Nicaragua', uk: 'Нікарагуа', ru: 'Никарагуа' },
    callingCode: '505',
    regex: '^(\\+505|505)?[2-9]\\d{7}$',
    mask: 'XXXX XXXX',
    placeholder: '8123 4567',
  },
  NE: {
    icon: '🇳🇪',
    countryCode: 'NE',
    countryName: { en: 'Niger', uk: 'Нігер', ru: 'Нигер' },
    callingCode: '227',
    regex: '^(\\+227|227)?[7-9]\\d{7}$',
    mask: 'XX XX XX XX',
    placeholder: '93 12 34 56',
  },
  NG: {
    icon: '🇳🇬',
    countryCode: 'NG',
    countryName: { en: 'Nigeria', uk: 'Нігерія', ru: 'Нигерия' },
    callingCode: '234',
    regex: '^(\\+234|234)?[7-9]\\d{9}$',
    mask: 'XXX XXX XXXX',
    placeholder: '802 123 4567',
  },
  KP: {
    icon: '🇰🇵',
    countryCode: 'KP',
    countryName: {
      en: 'North Korea',
      uk: 'Північна Корея',
      ru: 'Северная Корея',
    },
    callingCode: '850',
    regex: '^(\\+850|850)?[1-9]\\d{7}$',
    mask: 'XXX XXX XXXX',
    placeholder: '192 123 4567',
  },
  NO: {
    icon: '🇳🇴',
    countryCode: 'NO',
    countryName: { en: 'Norway', uk: 'Норвегія', ru: 'Норвегия' },
    callingCode: '47',
    regex: '^(\\+47|47)?[2-9]\\d{7}$',
    mask: 'XXX XX XXX',
    placeholder: '406 12 345',
  },
  OM: {
    icon: '🇴🇲',
    countryCode: 'OM',
    countryName: { en: 'Oman', uk: 'Оман', ru: 'Оман' },
    callingCode: '968',
    regex: '^(\\+968|968)?[7-9]\\d{7}$',
    mask: 'XXXX XXXX',
    placeholder: '9212 3456',
  },
  PK: {
    icon: '🇵🇰',
    countryCode: 'PK',
    countryName: { en: 'Pakistan', uk: 'Пакистан', ru: 'Пакистан' },
    callingCode: '92',
    regex: '^(\\+92|92)?[3-9]\\d{9}$',
    mask: 'XXX XXX XXXX',
    placeholder: '301 234 5678',
  },
  PA: {
    icon: '🇵🇦',
    countryCode: 'PA',
    countryName: { en: 'Panama', uk: 'Панама', ru: 'Панама' },
    callingCode: '507',
    regex: '^(\\+507|507)?[2-9]\\d{7}$',
    mask: 'XXXX-XXXX',
    placeholder: '6123-4567',
  },
  PG: {
    icon: '🇵🇬',
    countryCode: 'PG',
    countryName: {
      en: 'Papua New Guinea',
      uk: 'Папуа-Нова Гвінея',
      ru: 'Папуа-Новая Гвинея',
    },
    callingCode: '675',
    regex: '^(\\+675|675)?[2-9]\\d{6}$',
    mask: 'XXX XXXX',
    placeholder: '681 2345',
  },
  PY: {
    icon: '🇵🇾',
    countryCode: 'PY',
    countryName: { en: 'Paraguay', uk: 'Парагвай', ru: 'Парагвай' },
    callingCode: '595',
    regex: '^(\\+595|595)?[1-9]\\d{7}$',
    mask: 'XXX XXX XXX',
    placeholder: '961 123 456',
  },
  PE: {
    icon: '🇵🇪',
    countryCode: 'PE',
    countryName: { en: 'Peru', uk: 'Перу', ru: 'Перу' },
    callingCode: '51',
    regex: '^(\\+51|51)?9\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '912 345 678',
  },
  PH: {
    icon: '🇵🇭',
    countryCode: 'PH',
    countryName: { en: 'Philippines', uk: 'Філіппіни', ru: 'Филиппины' },
    callingCode: '63',
    regex: '^(\\+63|63)?9\\d{9}$',
    mask: 'XXX XXX XXXX',
    placeholder: '905 123 4567',
  },
  PL: {
    icon: '🇵🇱',
    countryCode: 'PL',
    countryName: { en: 'Poland', uk: 'Польща', ru: 'Польша' },
    callingCode: '48',
    regex: '^(\\+48|48)?[1-9]\\d{8}$',
    mask: 'XXX-XXX-XXX',
    placeholder: '512-345-678',
  },
  PT: {
    icon: '🇵🇹',
    countryCode: 'PT',
    countryName: { en: 'Portugal', uk: 'Португалія', ru: 'Португалия' },
    callingCode: '351',
    regex: '^(\\+351|351)?[2-9]\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '912 345 678',
  },
  PR: {
    icon: '🇵🇷',
    countryCode: 'PR',
    countryName: { en: 'Puerto Rico', uk: 'Пуерто-Ріко', ru: 'Пуэрто-Рико' },
    callingCode: '1787',
    regex: '^(\\+1787|1787)?[1-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '787-234-5678',
  },
  QA: {
    icon: '🇶🇦',
    countryCode: 'QA',
    countryName: { en: 'Qatar', uk: 'Катар', ru: 'Катар' },
    callingCode: '974',
    regex: '^(\\+974|974)?[3-9]\\d{7}$',
    mask: 'XXXX XXXX',
    placeholder: '3312 3456',
  },
  RO: {
    icon: '🇷🇴',
    countryCode: 'RO',
    countryName: { en: 'Romania', uk: 'Румунія', ru: 'Румыния' },
    callingCode: '40',
    regex: '^(\\+40|40)?[1-9]\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '712 345 678',
  },
  RU: {
    icon: '🇷🇺',
    countryCode: 'RU',
    countryName: { en: 'Russia', uk: 'Росія', ru: 'Россия' },
    callingCode: '7',
    regex: '^(\\+7|7)?[1-9]\\d{9}$',
    mask: 'XXX XXX-XX-XX',
    placeholder: '912 345-67-89',
  },
  RW: {
    icon: '🇷🇼',
    countryCode: 'RW',
    countryName: { en: 'Rwanda', uk: 'Руанда', ru: 'Руанда' },
    callingCode: '250',
    regex: '^(\\+250|250)?[7-9]\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '720 123 456',
  },
  KN: {
    icon: '🇰🇳',
    countryCode: 'KN',
    countryName: {
      en: 'Saint Kitts and Nevis',
      uk: 'Сент-Кітс і Невіс',
      ru: 'Сент-Китс и Невис',
    },
    callingCode: '1869',
    regex: '^(\\+1869|1869)?[2-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '869-765-1234',
  },
  SC: {
    icon: '🇸🇨',
    countryCode: 'SC',
    countryName: { en: 'Seychelles', uk: 'Сейшели', ru: 'Сейшелы' },
    callingCode: '248',
    regex: '^(\\+248|248)?[2-9]\\d{6}$',
    mask: 'X XXX XXX',
    placeholder: '2 510 123',
  },
  LC: {
    icon: '🇱🇨',
    countryCode: 'LC',
    countryName: { en: 'Saint Lucia', uk: 'Сент-Люсія', ru: 'Сент-Люсия' },
    callingCode: '1758',
    regex: '^(\\+1758|1758)?[2-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '758-284-5678',
  },
  SM: {
    icon: '🇸🇲',
    countryCode: 'SM',
    countryName: { en: 'San Marino', uk: 'Сан-Марино', ru: 'Сан-Марино' },
    callingCode: '378',
    regex: '^(\\+378|378)?[2-9]\\d{5}$',
    mask: 'XXXX XXXXXX',
    placeholder: '6612 3456',
  },
  ST: {
    icon: '🇸🇹',
    countryCode: 'ST',
    countryName: {
      en: 'São Tomé and Príncipe',
      uk: 'Сан-Томе і Принсіпі',
      ru: 'Сан-Томе и Принсипи',
    },
    callingCode: '239',
    regex: '^(\\+239|239)?[2-9]\\d{6}$',
    mask: 'XXX XXXX',
    placeholder: '981 2345',
  },
  SA: {
    icon: '🇸🇦',
    countryCode: 'SA',
    countryName: {
      en: 'Saudi Arabia',
      uk: 'Саудівська Аравія',
      ru: 'Саудовская Аравия',
    },
    callingCode: '966',
    regex: '^(\\+966|966)?[5-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '50 123 4567',
  },
  SN: {
    icon: '🇸🇳',
    countryCode: 'SN',
    countryName: { en: 'Senegal', uk: 'Сенегал', ru: 'Сенегал' },
    callingCode: '221',
    regex: '^(\\+221|221)?[7-9]\\d{7}$',
    mask: 'XX XXX XX XX',
    placeholder: '70 123 45 67',
  },
  RS: {
    icon: '🇷🇸',
    countryCode: 'RS',
    countryName: { en: 'Serbia', uk: 'Сербія', ru: 'Сербия' },
    callingCode: '381',
    regex: '^(\\+381|381)?[2-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '60 123 4567',
  },
  SG: {
    icon: '🇸🇬',
    countryCode: 'SG',
    countryName: { en: 'Singapore', uk: 'Сінгапур', ru: 'Сингапур' },
    callingCode: '65',
    regex: '^(\\+65|65)?[3-9]\\d{7}$',
    mask: 'XXXX XXXX',
    placeholder: '8123 4567',
  },
  SX: {
    icon: '🇸🇽',
    countryCode: 'SX',
    countryName: { en: 'Sint Maarten', uk: 'Сінт-Мартен', ru: 'Синт-Мартен' },
    callingCode: '1721',
    regex: '^(\\+1721|1721)?[2-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '721-545-1234',
  },
  SK: {
    icon: '🇸🇰',
    countryCode: 'SK',
    countryName: { en: 'Slovakia', uk: 'Словаччина', ru: 'Словакия' },
    callingCode: '421',
    regex: '^(\\+421|421)?[2-9]\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '912 345 678',
  },
  SI: {
    icon: '🇸🇮',
    countryCode: 'SI',
    countryName: { en: 'Slovenia', uk: 'Словенія', ru: 'Словения' },
    callingCode: '386',
    regex: '^(\\+386|386)?[2-9]\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '31 234 567',
  },
  SO: {
    icon: '🇸🇴',
    countryCode: 'SO',
    countryName: { en: 'Somalia', uk: 'Сомалі', ru: 'Сомали' },
    callingCode: '252',
    regex: '^(\\+252|252)?[2-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '61 234 5678',
  },
  ZA: {
    icon: '🇿🇦',
    countryCode: 'ZA',
    countryName: {
      en: 'South Africa',
      uk: 'Південна Африка',
      ru: 'Южная Африка',
    },
    callingCode: '27',
    regex: '^(\\+27|27)?[6-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '71 123 4567',
  },
  KR: {
    icon: '🇰🇷',
    countryCode: 'KR',
    countryName: { en: 'South Korea', uk: 'Південна Корея', ru: 'Южная Корея' },
    callingCode: '82',
    regex: '^(\\+82|82)?[1-9]\\d{8}$',
    mask: 'XX-XXXX-XXXX',
    placeholder: '10-1234-5678',
  },
  SS: {
    icon: '🇸🇸',
    countryCode: 'SS',
    countryName: {
      en: 'South Sudan',
      uk: 'Південний Судан',
      ru: 'Южный Судан',
    },
    callingCode: '211',
    regex: '^(\\+211|211)?[1-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '91 123 4567',
  },
  ES: {
    icon: '🇪🇸',
    countryCode: 'ES',
    countryName: { en: 'Spain', uk: 'Іспанія', ru: 'Испания' },
    callingCode: '34',
    regex: '^(\\+34|34)?[6-9]\\d{8}$',
    mask: 'XXX XX XX XX',
    placeholder: '612 34 56 78',
  },
  LK: {
    icon: '🇱🇰',
    countryCode: 'LK',
    countryName: { en: 'Sri Lanka', uk: 'Шрі-Ланка', ru: 'Шри-Ланка' },
    callingCode: '94',
    regex: '^(\\+94|94)?[7-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '71 234 5678',
  },
  SD: {
    icon: '🇸🇩',
    countryCode: 'SD',
    countryName: { en: 'Sudan', uk: 'Судан', ru: 'Судан' },
    callingCode: '249',
    regex: '^(\\+249|249)?[1-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '91 123 4567',
  },
  SR: {
    icon: '🇸🇷',
    countryCode: 'SR',
    countryName: { en: 'Suriname', uk: 'Сурінам', ru: 'Суринам' },
    callingCode: '597',
    regex: '^(\\+597|597)?[7-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '741-2345',
  },
  SZ: {
    icon: '🇸🇿',
    countryCode: 'SZ',
    countryName: { en: 'Eswatini', uk: 'Есватіні', ru: 'Эсватини' },
    callingCode: '268',
    regex: '^(\\+268|268)?[2-9]\\d{6}$',
    mask: 'XXXX XXXX',
    placeholder: '7612 3456',
  },
  SE: {
    icon: '🇸🇪',
    countryCode: 'SE',
    countryName: { en: 'Sweden', uk: 'Швеція', ru: 'Швеция' },
    callingCode: '46',
    regex: '^(\\+46|46)?[2-9]\\d{7}$',
    mask: 'XX-XXX XX XX',
    placeholder: '70-123 45 67',
  },
  CH: {
    icon: '🇨🇭',
    countryCode: 'CH',
    countryName: { en: 'Switzerland', uk: 'Швейцарія', ru: 'Швейцария' },
    callingCode: '41',
    regex: '^(\\+41|41)?[2-9]\\d{7}$',
    mask: 'XX XXX XX XX',
    placeholder: '78 123 45 67',
  },
  SY: {
    icon: '🇸🇾',
    countryCode: 'SY',
    countryName: { en: 'Syria', uk: 'Сирія', ru: 'Сирия' },
    callingCode: '963',
    regex: '^(\\+963|963)?[1-9]\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '944 567 890',
  },
  TJ: {
    icon: '🇹🇯',
    countryCode: 'TJ',
    countryName: { en: 'Tajikistan', uk: 'Таджикистан', ru: 'Таджикистан' },
    callingCode: '992',
    regex: '^(\\+992|992)?9\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '91 123 4567',
  },
  TZ: {
    icon: '🇹🇿',
    countryCode: 'TZ',
    countryName: { en: 'Tanzania', uk: 'Танзанія', ru: 'Танзания' },
    callingCode: '255',
    regex: '^(\\+255|255)?[7-9]\\d{8}$',
    mask: 'XXX XXX XXX',
    placeholder: '621 234 567',
  },
  TH: {
    icon: '🇹🇭',
    countryCode: 'TH',
    countryName: { en: 'Thailand', uk: 'Таїланд', ru: 'Таиланд' },
    callingCode: '66',
    regex: '^(\\+66|66)?[8-9]\\d{8}$',
    mask: 'XX XXXX XXXX',
    placeholder: '81 234 5678',
  },
  TG: {
    icon: '🇹🇬',
    countryCode: 'TG',
    countryName: { en: 'Togo', uk: 'Того', ru: 'Того' },
    callingCode: '228',
    regex: '^(\\+228|228)?[2-9]\\d{6}$',
    mask: 'XX XX XX XX',
    placeholder: '90 11 23 45',
  },
  TO: {
    icon: '🇹🇴',
    countryCode: 'TO',
    countryName: { en: 'Tonga', uk: 'Тонга', ru: 'Тонга' },
    callingCode: '676',
    regex: '^(\\+676|676)?[2-9]\\d{5}$',
    mask: 'XXX XXXX',
    placeholder: '771 5123',
  },
  TT: {
    icon: '🇹🇹',
    countryCode: 'TT',
    countryName: {
      en: 'Trinidad and Tobago',
      uk: 'Тринідад і Тобаго',
      ru: 'Тринидад и Тобаго',
    },
    callingCode: '1868',
    regex: '^(\\+1868|1868)?[2-9]\\d{6}$',
    mask: 'XXX-XXXX',
    placeholder: '868-291-1234',
  },
  TN: {
    icon: '🇹🇳',
    countryCode: 'TN',
    countryName: { en: 'Tunisia', uk: 'Туніс', ru: 'Тунис' },
    callingCode: '216',
    regex: '^(\\+216|216)?[2-9]\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '20 123 456',
  },
  TR: {
    icon: '🇹🇷',
    countryCode: 'TR',
    countryName: { en: 'Turkey', uk: 'Туреччина', ru: 'Турция' },
    callingCode: '90',
    regex: '^(\\+90|90)?[5-9]\\d{9}$',
    mask: 'XXX XXX XXXX',
    placeholder: '501 234 5678',
  },
  TM: {
    icon: '🇹🇲',
    countryCode: 'TM',
    countryName: { en: 'Turkmenistan', uk: 'Туркменістан', ru: 'Туркменистан' },
    callingCode: '993',
    regex: '^(\\+993|993)?[1-9]\\d{8}$',
    mask: 'XX XXXXXX',
    placeholder: '65 123456',
  },
  TV: {
    icon: '🇹🇻',
    countryCode: 'TV',
    countryName: { en: 'Tuvalu', uk: 'Тувалу', ru: 'Тувалу' },
    callingCode: '688',
    regex: '^(\\+688|688)?[2-9]\\d{5}$',
    mask: 'XXXXX',
    placeholder: '90123',
  },
  UG: {
    icon: '🇺🇬',
    countryCode: 'UG',
    countryName: { en: 'Uganda', uk: 'Уганда', ru: 'Уганда' },
    callingCode: '256',
    regex: '^(\\+256|256)?[7-9]\\d{8}$',
    mask: 'XXX XXXXXX',
    placeholder: '712 345678',
  },
  UA: {
    icon: '🇺🇦',
    countryCode: 'UA',
    countryName: { en: 'Ukraine', uk: 'Україна', ru: 'Украина' },
    callingCode: '380',
    regex: '^(\\+380|380)?[1-9]\\d{8}$',
    mask: 'XX XXX XX XX',
    placeholder: '50 123 45 67',
  },
  AE: {
    icon: '🇦🇪',
    countryCode: 'AE',
    countryName: { en: 'United Arab Emirates', uk: 'ОАЕ', ru: 'ОАЭ' },
    callingCode: '971',
    regex: '^(\\+971|971)?[5-9]\\d{7}$',
    mask: 'XX XXX XXXX',
    placeholder: '50 123 4567',
  },
  GB: {
    icon: '🇬🇧',
    countryCode: 'GB',
    countryName: {
      en: 'United Kingdom',
      uk: 'Велика Британія',
      ru: 'Великобритания',
    },
    callingCode: '44',
    regex: '^(\\+44|44)?[1-9]\\d{9}$',
    mask: 'XXXX XXX XXXX',
    placeholder: '7400 123456',
  },
  US: {
    icon: '🇺🇸',
    countryCode: 'US',
    countryName: { en: 'United States', uk: 'США', ru: 'США' },
    callingCode: '1',
    regex: '^(\\+1|1)?[2-9]\\d{9}$',
    mask: '(XXX) XXX-XXXX',
    placeholder: '(201) 555-0123',
  },
  UY: {
    icon: '🇺🇾',
    countryCode: 'UY',
    countryName: { en: 'Uruguay', uk: 'Уругвай', ru: 'Уругвай' },
    callingCode: '598',
    regex: '^(\\+598|598)?[2-9]\\d{7}$',
    mask: 'XX XXX XXX',
    placeholder: '94 123 456',
  },
  UZ: {
    icon: '🇺🇿',
    countryCode: 'UZ',
    countryName: { en: 'Uzbekistan', uk: 'Узбекистан', ru: 'Узбекистан' },
    callingCode: '998',
    regex: '^(\\+998|998)?[1-9]\\d{8}$',
    mask: 'XX XXX XX XX',
    placeholder: '90 123 45 67',
  },
  VU: {
    icon: '🇻🇺',
    countryCode: 'VU',
    countryName: { en: 'Vanuatu', uk: 'Вануату', ru: 'Вануату' },
    callingCode: '678',
    regex: '^(\\+678|678)?[2-9]\\d{5}$',
    mask: 'XX XXXXX',
    placeholder: '59 12345',
  },
  VE: {
    icon: '🇻🇪',
    countryCode: 'VE',
    countryName: { en: 'Venezuela', uk: 'Венесуела', ru: 'Венесуэла' },
    callingCode: '58',
    regex: '^(\\+58|58)?[4-9]\\d{9}$',
    mask: 'XXX-XXX-XXXX',
    placeholder: '412-123-4567',
  },
  VN: {
    icon: '🇻🇳',
    countryCode: 'VN',
    countryName: { en: 'Vietnam', uk: "В'єтнам", ru: 'Вьетнам' },
    callingCode: '84',
    regex: '^(\\+84|84)?[1-9]\\d{8}$',
    mask: 'XXX XXX XXXX',
    placeholder: '091 234 5678',
  },
  WF: {
    icon: '🇼🇫',
    countryCode: 'WF',
    countryName: {
      en: 'Wallis and Futuna',
      uk: 'Волліс і Футуна',
      ru: 'Уоллис и Футуна',
    },
    callingCode: '681',
    regex: '^(\\+681|681)?[2-9]\\d{5}$',
    mask: 'XX XX XX',
    placeholder: '82 12 34',
  },
  YE: {
    icon: '🇾🇪',
    countryCode: 'YE',
    countryName: { en: 'Yemen', uk: 'Ємен', ru: 'Йемен' },
    callingCode: '967',
    regex: '^(\\+967|967)?[1-9]\\d{7}$',
    mask: 'XXX XXX XXX',
    placeholder: '712 345 678',
  },
  ZM: {
    icon: '🇿🇲',
    countryCode: 'ZM',
    countryName: { en: 'Zambia', uk: 'Замбія', ru: 'Замбия' },
    callingCode: '260',
    regex: '^(\\+260|260)?9\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '95 123 4567',
  },
  ZW: {
    icon: '🇿🇼',
    countryCode: 'ZW',
    countryName: { en: 'Zimbabwe', uk: 'Зімбабве', ru: 'Зимбабве' },
    callingCode: '263',
    regex: '^(\\+263|263)?[7-9]\\d{8}$',
    mask: 'XX XXX XXXX',
    placeholder: '71 234 5678',
  },
};

export default constants;
